CREATE TABLE if not exists users
(
    user_id  integer generated by default as identity PRIMARY KEY,
    login    varchar,
    name     varchar,
    birthday date,
    email    varchar
);

CREATE TABLE if not exists film
(
    film_id      integer generated by default as identity PRIMARY KEY,
    name         varchar,
    description  varchar,
    release_Date date,
    duration     integer,
    rating_id    integer
);

CREATE TABLE if not exists rating
(
    rating_id integer generated by default as identity PRIMARY KEY,
    name      varchar
);

CREATE TABLE if not exists genre
(
    genre_id integer generated by default as identity PRIMARY KEY,
    name     varchar
);

CREATE TABLE if not exists friendship
(
    user_id  integer,
    friend_id integer
);

CREATE TABLE if not exists likes
(
    film_id integer PRIMARY KEY,
    user_id integer
);

CREATE TABLE if not exists film_genre
(
    film_id  integer PRIMARY KEY,
    genre_id integer
);

ALTER TABLE if exists film
    ADD FOREIGN KEY (rating_id) REFERENCES rating (rating_id);

ALTER TABLE if exists film_genre
    ADD FOREIGN KEY (film_id) REFERENCES film (film_id);

ALTER TABLE if exists film_genre
    ADD FOREIGN KEY (genre_id) REFERENCES genre (genre_id);

ALTER TABLE if exists likes
    ADD FOREIGN KEY (film_id) REFERENCES film (film_id);

ALTER TABLE if exists likes
    ADD FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE if exists friendship
    ADD FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE if exists friendship
    ADD FOREIGN KEY (friend_id) REFERENCES users (user_id);
