CREATE TABLE users (
                      user_id integer generated by default as identity PRIMARY KEY,
                      login varchar,
                      name varchar,
                      birthday date,
                      email varchar
);

CREATE TABLE film (
                      film_id integer generated by default as identity PRIMARY KEY,
                      name varchar,
                      description varchar,
                      release_Date date,
                      duration integer,
                      rating_id integer
);

CREATE TABLE rating (
                      rating_id integer generated by default as identity PRIMARY KEY,
                      name varchar
);

CREATE TABLE genre (
                       genre_id integer generated by default as identity PRIMARY KEY,
                       name varchar
);

CREATE TABLE friendship (
                            user_id integer PRIMARY KEY,
                            user_id2 integer,
                            exist boolean
);

CREATE TABLE likes (
                       film_id integer PRIMARY KEY,
                       user_id integer
);

CREATE TABLE film_genre (
                            film_id integer PRIMARY KEY,
                            genre_id integer
);

ALTER TABLE film ADD FOREIGN KEY (rating_id) REFERENCES rating (rating_id);

ALTER TABLE film_genre ADD FOREIGN KEY (film_id) REFERENCES film (film_id);

ALTER TABLE film_genre ADD FOREIGN KEY (genre_id) REFERENCES genre (genre_id);

ALTER TABLE likes ADD FOREIGN KEY (film_id) REFERENCES film (film_id);

ALTER TABLE likes ADD FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE friendship ADD FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE friendship ADD FOREIGN KEY (user_id2) REFERENCES users (user_id);
